server:
  port: 9890
  tomcat:
      uri-encoding: UTF-8

spring:
  application:
    name: eureka-service

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka-service/



