server:
  port: 9899

spring:
  application:
    name: zuul-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9890/eureka/

#spring:
#  boot:
#    admin:
#      url: http://localhost:9690

#Error: {"timestamp":1502748955345,"status":401,"error":"Unauthorized","message":"Full authentication is required to access this resource.","path":"/env"}
#Error: {"timestamp":1502748975573,"status":401,"error":"Unauthorized","message":"Full authentication is required to access this resource.","path":"/metrics"}
#resolved up problems
#management:
#  security:
#    enabled: false

# routes to serviceId,simple cases,wo usually use eureka client to discovery the service instead of to configure it like down below

#zuul:
#  routes:
#    consumer:
#      serviceId: ribbon-consumer
#      path: /ribbon-consumer
#    provider:
#      serviceId: ribbon-provider
#      path: /ribbon-provider



